version: '3'
services:
  om-nginx:
    build:
      context: ./docker/development
      dockerfile: nginx.docker
    volumes:
      - ./:/app
    depends_on:
      - om-php-fpm
    ports:
      - "8080:80"
  om-php-fpm:
    build:
      context: ./docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./:/app
    links:
      - om-pgsql
      - om-redis
      - mailer
  om-php-cli:
    build:
      context: ./docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./:/app
    links:
      - om-pgsql
      - om-redis
      - mailer
  om-pgsql:
    image: postgres:11.2-alpine
    volumes:
      - ./storage/docker/pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: om
    ports:
      - "54321:5432"
  om-redis:
    build:
      context: ./docker/development
      dockerfile: redis.docker
  mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"
